version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file:
      - buttonymood.art.prod.env
    environment:
      - MYSQL_DATABASE=buttonymood
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
  wordpress:
    depends_on:
      - db
    image: wordpress:5.8.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - buttonymood.art.prod.env
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=buttonymood
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
  nginx:
    depends_on:
      - wordpress
    image: nginx:1.20-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network
  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email info@buttonymood.art --agree-tos --no-eff-email --staging -d buttonymood.art -d www.buttonymood.art

volumes:
  certbot-etc:
  wordpress:
  dbdata:
networks:
  app-network:
    driver: bridge
